sudo: false
language: node_js
node_js:
  - '8'
  - '10'

env:
  matrix:
    - MONGODB=3.4.16
    - MONGODB=3.6.6
    - MONGODB=4.0.0

matrix:
  fast_finish: true

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - npm i npminstall && npminstall

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

script:
  - npm test

after_script:
  - nyc report --reporter=text-lcov > coverage.lcov
  - npminstall codecov && codecov
